#!/usr/bin/env python3
"""Prepare a deterministic Labuco catalog for autonomous Supabase import.

Input: GrowTent products.json generated by growtent_catalog_importer.py.
Output: compact JSON array matching public.labuco_import_batch(payload).

The script is intentionally dependency-free and idempotent. It validates IDs,
prices and uniqueness before publishing a catalog that GitHub Actions can commit
and the Supabase Edge Function can consume without user interaction.
"""
from __future__ import annotations

import argparse
import json
import re
from decimal import Decimal, ROUND_HALF_UP
from pathlib import Path

MONEY_RE = re.compile(r"(-?\d[\d\s]*(?:[.,]\d{1,2})?)")

BRANDS = sorted([
    "Advanced Nutrients", "GHE - Terra Aquatica", "Shogun Fertilisers",
    "Aqua Master Tools", "Cornwall Electronics", "Neptune Hydroponics",
    "Powder Feeding", "Secret Jardin", "AC Infinity", "PRIMA KLIMA",
    "Root Pouch", "Tropf Blumat", "Can-Filters", "Vents-Group",
    "Aptus Holland", "Black Orchid", "W. Legutko", "Trol Master",
    "Spider Farmer", "Mars Hydro", "RoyalRoom", "Homebox", "CANNA",
    "Canna", "AutoPot", "Plagron", "Garland", "BioBizz", "Biotabs",
    "BAC", "Hesi", "ONA", "Can-Fan", "Milwaukee", "Guanokalong",
    "ATHENA", "Jiffy", "LUMATEK", "Top Crop", "Bluelab", "DonKwiat",
    "Dutchpro", "Cannaboom", "Biovita", "Lumatek", "Terra Aquatica",
], key=len, reverse=True)

CATEGORY_RULES = [
    ("Growboxy i namioty", r"growbox|namiot|homebox|secret jardin|royalroom|dark room"),
    ("Oświetlenie", r"\bled\b|hps|\bmh\b|cmh|cfl|lampa|zarowk|żarówk|odblysnik|odbłyśnik|ballast|statecznik"),
    ("Wentylacja i klimat", r"wentyl|filtr.*wegl|filtr.*węgl|carbon filter|can.?fan|can.?filters|nawilzacz|nawilżacz|osuszacz|higrostat"),
    ("Nawozy i stymulatory", r"nawoz|nawóz|fertili|plagron|canna|biobizz|advanced nutrients|hesi|aptus|bac|booster|stymulator|bloom|grow|roots|enzym|ph plus|ph minus"),
    ("Podłoża i media", r"coco|kokos|keramzyt|perlit|rockwool|welna mineral|wełna mineral|ziemia|soil|substrat|podloze|podłoże"),
    ("Doniczki, tace i pojemniki", r"doniczk|fabric pot|root pouch|air.?pot|net pot|\btac[ae]\b|tray|podstawk|zbiornik|pojemnik"),
    ("Nawadnianie i hydroponika", r"autopot|blumat|kropl|dripper|pompa.*wod|water pump|hydropon|\bdwc\b|napowietrz"),
    ("Pomiary i automatyka", r"miernik|ph meter|ec meter|tds|termometr|higrometr|kalibr|elektrod|kontroler|controller|timer|programator"),
]

GENERIC_PREFIXES = {
    "nawoz", "nawóz", "zestaw", "lampa", "lampy", "wentylator", "filtr",
    "doniczka", "doniczki", "miernik", "podloze", "podłoże", "ziemia",
    "system", "pompa", "akcesoria", "akcesorium", "growbox", "namiot",
}


def parse_money(value) -> Decimal:
    if value is None:
        raise ValueError("missing price")
    m = MONEY_RE.search(str(value).replace("\xa0", " "))
    if not m:
        raise ValueError(f"cannot parse price: {value!r}")
    return Decimal(m.group(1).replace(" ", "").replace(",", "."))


def target_markup(cost: Decimal) -> Decimal:
    if cost <= Decimal("50"): return Decimal("0.25")
    if cost <= Decimal("150"): return Decimal("0.20")
    if cost <= Decimal("300"): return Decimal("0.17")
    if cost <= Decimal("700"): return Decimal("0.14")
    return Decimal("0.11")


def round_to_90(value: Decimal) -> Decimal:
    whole = value.to_integral_value(rounding="ROUND_FLOOR")
    candidate = whole + Decimal("0.90")
    if candidate < value:
        candidate += Decimal("1.00")
    return candidate.quantize(Decimal("0.01"), rounding=ROUND_HALF_UP)


def classify_price(cost: Decimal, retail: Decimal) -> str:
    profit = retail - cost
    markup = profit / cost if cost else Decimal("0")
    if markup >= Decimal("0.15") and profit >= Decimal("8"): return "A"
    if markup >= Decimal("0.08") and profit >= Decimal("3"): return "B"
    return "C"


def normalize_title(title: str) -> str:
    title = re.sub(r"\s+", " ", title or "").strip()
    title = re.sub(r"\bNawoz\b", "Nawóz", title, flags=re.I)
    title = re.sub(r"\bodzywka\b", "odżywka", title, flags=re.I)
    return title


def guess_brand(title: str) -> str:
    low = title.lower()
    for brand in BRANDS:
        if brand.lower() in low:
            return "Canna" if brand.upper() == "CANNA" else brand
    tokens = re.findall(r"[A-Za-zÀ-ž0-9&!+.-]+", title)
    while tokens and tokens[0].lower() in GENERIC_PREFIXES:
        tokens.pop(0)
    if not tokens:
        return "Labuco"
    if len(tokens) >= 2 and len(tokens[0]) <= 3 and tokens[1][0:1].isupper():
        return f"{tokens[0]} {tokens[1]}"[:80]
    return tokens[0][:80]


def categorize(title: str) -> str:
    low = title.lower()
    for category, pattern in CATEGORY_RULES:
        if re.search(pattern, low, re.I):
            return category
    return "Akcesoria do uprawy"


def sku_for(source_id: str) -> str:
    try:
        return f"LAB-{int(source_id):05d}"
    except Exception:
        safe = re.sub(r"[^A-Za-z0-9_-]+", "-", source_id).strip("-")
        return f"LAB-{safe}"[:64]


def prices_for(row: dict) -> tuple[Decimal, Decimal, str, bool, str]:
    """Return cost, retail, class, review flag and an auditable price source."""
    b2b_gross = row.get("price_b2b_gross")
    b2b_net = row.get("price_b2b_net")
    retail_reference = row.get("price_retail_gross")

    if b2b_gross not in (None, "") or b2b_net not in (None, ""):
        if b2b_gross not in (None, ""):
            cost = parse_money(b2b_gross)
            source = "b2b_gross"
        else:
            cost = parse_money(b2b_net)
            source = "b2b_net"
        target = round_to_90(cost * (Decimal("1") + target_markup(cost)))
        market = parse_money(retail_reference) if retail_reference not in (None, "") else None
        if market is not None:
            competitive_cap = round_to_90(market * Decimal("0.985"))
            retail = max(cost + Decimal("0.01"), min(target, competitive_cap))
        else:
            retail = target
        return cost, retail, classify_price(cost, retail), market is None, source

    public_retail = (
        retail_reference
        or row.get("price_pln")
        or row.get("price")
        or row.get("source_price_with_question")
        or row.get("source_price")
    )
    cost_proxy = parse_money(public_retail)
    # A public retail price is not a wholesale cost. Keep the record useful as
    # a catalog reference but class it C, which the guarded Spree importer skips
    # unless a human explicitly opts in after validating supplier terms.
    return cost_proxy, cost_proxy, "C", True, "public_retail_reference"


def first_reference_image(row: dict) -> str | None:
    direct = row.get("reference_image") or row.get("image")
    if direct:
        return direct
    images = row.get("images")
    if isinstance(images, list):
        return next((image for image in images if image), None)
    return None


def prepare(row: dict) -> dict:
    source_id = str(row.get("id") or row.get("source_id") or "").strip()
    if not source_id:
        raise ValueError("missing source id")
    title = normalize_title(str(row.get("title") or ""))
    if not title:
        raise ValueError(f"{source_id}: missing title")
    cost, retail, price_class, market_check_required, price_source = prices_for(row)
    if cost <= 0:
        raise ValueError(f"{source_id}: non-positive price")
    brand = normalize_title(str(row.get("producer") or row.get("brand") or "")) or guess_brand(title)
    category = categorize(title)
    description = (
        f"{title}. Produkt marki {brand} z kategorii {category}. "
        "Pozycja katalogowa Labuco do legalnej uprawy indoor i ogrodnictwa. "
        "Przed zakupem należy sprawdzić wariant, kompatybilność i zalecenia producenta."
    )
    return {
        "labuco_sku": sku_for(source_id),
        "source_id": source_id,
        "brand": brand,
        "title": title,
        "short_description": f"{title} — {brand}, {category}.",
        "description": description,
        "category": category,
        "wholesale_cost_pln": f"{cost:.2f}",
        "labuco_price_pln": f"{retail:.2f}",
        "price_class": price_class,
        "source_url": row.get("url") or row.get("source_url"),
        "reference_image": first_reference_image(row),
        "final_image_status": "REFERENCYJNE_ZRODLO_GROWTENT",
        "external_image_search_query": f"{title} {brand} official product image",
        "image_brief": f"Packshot e-commerce: {title}, marka {brand}. Neutralne tło, bez znaków wodnych.",
        "market_check_required": market_check_required,
        "raw": {
            "source": row.get("source"),
            "source_sku": row.get("sku"),
            "ean": row.get("ean"),
            "availability": row.get("availability"),
            "quantity_available": row.get("quantity_available"),
            "currency": row.get("currency"),
            "price_source": price_source,
            "price_retail_gross": row.get("price_retail_gross"),
            "price_b2b_gross": row.get("price_b2b_gross"),
            "price_b2b_net": row.get("price_b2b_net"),
            "vat": row.get("vat"),
            "categories": row.get("categories"),
            "attributes": row.get("attributes"),
        },
    }


def numeric_key(row: dict):
    sid = str(row.get("id") or row.get("source_id") or "")
    try: return (0, int(sid))
    except Exception: return (1, sid)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("input", type=Path)
    ap.add_argument("output", type=Path)
    ap.add_argument("--limit", type=int, default=3316)
    args = ap.parse_args()

    source = json.loads(args.input.read_text(encoding="utf-8"))
    if not isinstance(source, list):
        raise SystemExit("Input must be a JSON array")

    prepared, errors, seen_ids, seen_skus = [], [], set(), set()
    for row in sorted(source, key=numeric_key):
        if len(prepared) >= args.limit:
            break
        try:
            item = prepare(row)
            if item["source_id"] in seen_ids:
                raise ValueError(f"duplicate source_id {item['source_id']}")
            if item["labuco_sku"] in seen_skus:
                raise ValueError(f"duplicate sku {item['labuco_sku']}")
            seen_ids.add(item["source_id"]); seen_skus.add(item["labuco_sku"])
            prepared.append(item)
        except Exception as exc:
            errors.append({"id": row.get("id"), "title": row.get("title"), "error": str(exc)})

    if len(prepared) < args.limit:
        raise SystemExit(f"Prepared only {len(prepared)} valid products; expected {args.limit}; errors={len(errors)}")

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(json.dumps(prepared, ensure_ascii=False, separators=(",", ":")), encoding="utf-8")
    summary = {
        "prepared": len(prepared),
        "errors_skipped_before_limit": len(errors),
        "unique_source_ids": len(seen_ids),
        "unique_skus": len(seen_skus),
        "first_sku": prepared[0]["labuco_sku"],
        "last_sku": prepared[-1]["labuco_sku"],
    }
    args.output.with_suffix(".summary.json").write_text(json.dumps(summary, ensure_ascii=False, indent=2), encoding="utf-8")
    print(json.dumps(summary, ensure_ascii=False))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
